# Generated by Django 4.1.11 on 2023-09-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 8, 53, 45, 923335, tzinfo=datetime.timezone.utc)),
        ),
    ]
